//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SneakerSportStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonDatHang
    {
        public int ChiTietDonDatHangID { get; set; }
        public Nullable<int> DonDatHangID { get; set; }
        public Nullable<int> GiayID { get; set; }
        public int SoLuong { get; set; }
        public decimal GiaBan { get; set; }
    
        public virtual DonDatHang DonDatHang { get; set; }
        public virtual Giay Giay { get; set; }
    }
}
