//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SneakerSportStore.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Giay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Giay()
        {
            this.ChiTietDonDatHangs = new HashSet<ChiTietDonDatHang>();
            this.ThongSoKyThuats = new HashSet<ThongSoKyThuat>();
        }
        //public string FirebaseKey { get; set; } 
        public string GiayId { get; set; } 

        public string TenGiay { get; set; }
        public decimal Gia { get; set; }
        public int SoLuongTon { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> NhaSanXuatID { get; set; }
        public Nullable<int> LoaiGiayID { get; set; }
        public string HinhAnh { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonDatHang> ChiTietDonDatHangs { get; set; }
        public virtual LoaiGiay LoaiGiay { get; set; }
        public virtual NhaSanXuat NhaSanXuat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongSoKyThuat> ThongSoKyThuats { get; set; }
    }
}