//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SneakerSportStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongSoKyThuat
    {
        public int ThongSoID { get; set; }
        public Nullable<int> GiayID { get; set; }
        public string KichCo { get; set; }
        public string MauSac { get; set; }
        public string ChatLieu { get; set; }
    
        public virtual Giay Giay { get; set; }
    }
}
